### PR TITLE
Update Skjema - Bestilling laboratorieanalyser og dataforvaltning.xlsm

### PR DESCRIPTION
**Pull request by jeved**
In branch Analysismethod-all-listed the sheet "Analyserekvisisjon ferskvann" have all analysismethods ready listed, and the user doesn't have to pick each analysis. This is as proposed by @DagHjermann at yesterdays Vannmiljø reporting meeting.

Is this a better way to do it, or should we stick to the selection of methods like the way it is in the other schemas?

### CODE REVIEW

**Comment by roarbra** [comment]
I think this was a better approach. It was easier to see which alternatives there is, and I think more efficient when you're going for several analysis.

**Comment by DagHjermann** [comment]
I agree, I think this new version looked good! (And as Ferskvann has the longest list the others should be ok too.) Remember to add som extra empty rows for analyses not included in the list (as suggested by yourself :-). Also I noted that it says "PCB (Polyklorerte bifenyler)" in two of the methods and just "PCB" in two others; I don't know how these values are used further on, so I don't know if that is a potential trouble-maker.

**Comment by KristofferKa** [comment]
As discussed. It's an extensive template and (still probably) more "complicated" than the users would prefer, but I guess it's pretty hard to avoid (i.e. inevitable) given our internal processes.

Thumbs up.

**Comment by jeved** [comment]
Thanks for the comments. I will present the "Analyserekvisisjon ferskvann" with the full list exposed to Anna Luise.

The PCBs should be corrected. I got the list from Anna Luise, I will notify her.

Regarding extra empty lines for other analyses as commented by @DagHjermann, the user can press the "Ny analyse" button to achieve this henself

**Comment by jeved** [comment]
And yes, the order form is getting complicated, I think it reflects both that we are performing complicated projects in NIVA, as @KristofferKa states, and that maybe Excel isnt the best platform for this. Maybe some future changes in Excel can help a tiny bit, and maybe it would be a good idea to split ordering of data management from lab. But lets discuss that later

**Comment by DagHjermann** [comment]
I don't think this order form is complex at all. It is dead simple compared to the actual plan of which parameters should be taken for which tissues from which species at which station. [Example](K:\Prosjekter\Sjøvann\JAMP\2018\analyser\MILKYS+Lange tidsserier - analyser 2018.xlsx)  from the Milkys project (check sheets "TORSK" and "BLÅSKJELL"). But the form is (often) double work since the researchers usually have already made these kind of plans on their own Excel sheets. But the amount of double work is, I would say, pretty small.

**Comment by jeved** [comment]
Anne Luise wasn't happy with the listing of all analysismethods in the "Analyserekvisisjon Ferskvann" sheet/template. She suggested to make buttons for hiding unchecked rows. I have implemented that, and as well as introduced cell protection, to prevent the users from hacking up the sheet along with various other improvements. Can all have a look now, if OK I will present it to the lab again

**Pull request merged**
